name: Auto-update Gemfiles

# This action cannot be skipped altogether because it is a mandatory status check.
# Instead we conditionally skip it at job level, instead of workflow level.
on:
  pull_request:
    paths:
      - 'tasks/edge.rake'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'appraisal/**'
      - 'gemfiles/**'
  workflow_dispatch:
    

# Ensure obsolete job is cancelled if another commit is pushed to the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-gemfiles:
    name: Auto-update Gemfiles
    runs-on: ubuntu-22.04
    permissions:
        pull-requests: write
    strategy:
        matrix:
            ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2']

    steps:
      # Only execute if there's a PR attached to this branch.
      # Because we execute on `push`, we have to double check here if this is part of a PR.
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Check for changes in Gemfiles and related files
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          filters: |
            gemfile:
              - Gemfile
              - Appraisals
              - datadog.gemspec
              - tasks/appraisal.rake
              - .github/workflows/update-gemfiles.yml
              - lib/datadog/version.rb
              - 'appraisal/**'
              - 'gemfiles/**'

      - name: Build gem
        run: |
            bundle exec rake edge:update

    #   - name: Create Pull Request
    #     id: pr
    #     uses: peter-evans/create-pull-request@v7
    #     with:
    #         token: ${{ secrets.GITHUB_TOKEN }}
    #         branch: "upgrade-gemfiles"
    #         commit-message: "Test updating gemfiles"
    #         delete-branch: true
    #         base: master
    #         title: "chore: update gemfiles"
    #         body: Test updating gemfiles.